name: Manually push pbench.agent collection into galaxy

on: 
  workflow_dispatch:
  
  push:
    branches: 
      - agent
      - server

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Push to Galaxy
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          
